name: Publish a PyPi-compatible Index

on:
  workflow_call:
  push:

jobs:
  publish_pypi_index:
    name: Build a PyPI-compatible index
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      packages: read
      pages: write
      id-token: write
    steps:    
      - uses: actions/checkout@v2

      - name: Generate Package Index
        run: |        
          python -m pip install --upgrade pip
          pip install PyGithub
          python .github/scripts/generate_index.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_DIR: dist

      - name: Upload Site Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
